# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5cce937949ff2c25942e18c838d6321ec643e317786f085829610807bfe8fdc41c25dd520457b7adc09c212e29eab7e8b7ac2ccdf7e88831f2dd1ba715d137

test:
  secret_key_base: b5346b5eb6e958c8a135cbecce41fb96e415539de8f65b74943ba3f59c96c524b3f80c70130f1cd2188ff513df7c74660eaa14d1047d65d263e3e1a67ff9a910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
